//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.EntityFramework.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> InRepair { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
