//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.EntityFramework.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessGymEntities : DbContext
    {
        public FitnessGymEntities()
            : base("name=FitnessGymEntities")
        {
        }
        private static FitnessGymEntities context;

        public static FitnessGymEntities GetContext()
        {
            if (context == null)
            {
                context = new FitnessGymEntities();
            }
            return context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Statts> Statts { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Visitors> Visitors { get; set; }
        public virtual DbSet<Workouts> Workouts { get; set; }
    }
}
