//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.EntityFramework.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statts
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public Nullable<decimal> TotalSubscriptionsRevenue { get; set; }
        public Nullable<decimal> TrainersSalaryExpense { get; set; }
        public Nullable<decimal> ManagersSalaryExpense { get; set; }
        public Nullable<decimal> RepairCosts { get; set; }
        public Nullable<decimal> EquipmentPurchaseCosts { get; set; }
    }
}
