//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.EntityFramework.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitors
    {
        public System.Guid ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string SubscriptionType { get; set; }
        public string SubscriptionStatus { get; set; }
        public Nullable<System.DateTime> SubscriptionStart { get; set; }
        public Nullable<System.DateTime> SubscriptionEnd { get; set; }
        public Nullable<decimal> SubscriptionPrice { get; set; }
    }
}
